const mongoose = require("mongoose");
const db = require("../db/models/index");

mongoose.connect(
    process.env.MONGODB_URI ||
    "mongodb://localhost/Users"
);

//QB Seed
const qbSeed = [
    {
        name: "Patrick Mahomes II",
        avgPocketTime: 2.0,
        completionPercentage: 0.45,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08282018/30123.png",
        currentTeam: "KC",
        vsDefenseCompletionPercentage: {
            "ATL": 0.45,
            "ARI": 0.45,
            "BAL": 0.45,
            "BUF": 0.45,
            "CAR": 0.45,
            "CHI": 0.45,
            "CIN": 0.45,
            "CLE": 0.45,
            "DAL": 0.45,
            "DEN": 0.45,
            "DET": 0.45,
            "GB": 0.45,
            "HOU": 0.45,
            "IND": 0.45,
            "JAX": 0.45,
            "KC": 0.45,
            "LAC": 0.45,
            "LAR": 0.45,
            "MIA": 0.45,
            "MIN": 0.45,
            "NE": 0.45,
            "NO": 0.45,
            "NYG": 0.45,
            "NYJ": 0.45,
            "OAK": 0.45,
            "PHI": 0.45,
            "PIT": 0.45,
            "SEA": 0.45,
            "SF": 0.45,
            "TB": 0.45,
            "TEN": 0.45,
            "WAS": 0.45,
        }
    },
    {
        name: "Andy Dalton",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08222018/24822.png",
        currentTeam: "CIN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Andrew Luck",
        avgPocketTime: 2.2,
        completionPercentage: 0.33,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09212017/25711.png",
        currentTeam: "IND",
        vsDefenseCompletionPercentage: {
            "ATL": 0.33,
            "ARI": 0.33,
            "BAL": 0.33,
            "BUF": 0.33,
            "CAR": 0.33,
            "CHI": 0.33,
            "CIN": 0.33,
            "CLE": 0.33,
            "DAL": 0.33,
            "DEN": 0.33,
            "DET": 0.33,
            "GB": 0.33,
            "HOU": 0.33,
            "IND": 0.33,
            "JAX": 0.33,
            "KC": 0.33,
            "LAC": 0.33,
            "LAR": 0.33,
            "MIA": 0.33,
            "MIN": 0.33,
            "NE": 0.33,
            "NO": 0.33,
            "NYG": 0.33,
            "NYJ": 0.33,
            "OAK": 0.33,
            "PHI": 0.33,
            "PIT": 0.33,
            "SEA": 0.33,
            "SF": 0.33,
            "TB": 0.33,
            "TEN": 0.33,
            "WAS": 0.33
        }
    },
    {
        name: "Tom Brady",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08272018/5228.png",
        currentTeam: "NE",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Drew Brees",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08252018/5479.png",
        currentTeam: "NO",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Eli Manning",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09242018/6760.png",
        currentTeam: "NYG",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Josh McCown",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08272018/5967.png",
        currentTeam: "NYJ",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Derek Anderson",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08222017/7389.png",
        currentTeam: "BUF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Philip Rivers",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08262018/6763.png",
        currentTeam: "LAC",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Aaron Rodgers",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08212018/7200.png",
        currentTeam: "GB",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Ben Roethlisberger",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08212018/6770.png",
        currentTeam: "PIT",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Alex Smith",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09302018/7177.png",
        currentTeam: "WAS",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Ryan Fitzpatrick",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09272018/7426.png",
        currentTeam: "TB",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Joe Flacco",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09272018/8795.png",
        currentTeam: "BAL",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Matt Ryan",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08222018/8780.png",
        currentTeam: "ATL",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Matthew Stafford",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08272018/9265.png",
        currentTeam: "DET",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Cam Newton",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08212018/24788.png",
        currentTeam: "CAR",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Ryan Tannehill",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09242018/25718.png",
        currentTeam: "MIA",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Kirk Cousins",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08222018/25812.png",
        currentTeam: "MIN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Nick Foles",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08212018/25798.png",
        currentTeam: "PHI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Case Keenum",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09122018/26483.png",
        currentTeam: "DEN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Brock Osweiler",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09242018/25767.png",
        currentTeam: "MIA",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Russell Wilson",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08212018/25785.png",
        currentTeam: "SEA",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Blake Bortles",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08232018/27531.png",
        currentTeam: "JAX",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Derek Carr",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09072018/27564.png",
        currentTeam: "OAK",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Marcus Mariota",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08232018/28390.png",
        currentTeam: "TEN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Jameis Winston",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09272018/28389.png",
        currentTeam: "TB",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Jared Goff",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09102018/29235.png",
        currentTeam: "LAR",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Dak Prescott",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09272018/29369.png",
        currentTeam: "DAL",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Carson Wentz",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08212018/29236.png",
        currentTeam: "PHI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "C.J. Beathard",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08202018/30217.png",
        currentTeam: "SF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Nathan Peterman",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08232018/30284.png",
        currentTeam: "BUF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Mitchell Trubisky",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08282018/30115.png",
        currentTeam: "CHI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Deshaun Watson",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08212018/30125.png",
        currentTeam: "HOU",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Josh Allen",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08232018/30977.png",
        currentTeam: "BUF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Sam Darnold",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08272018/30973.png",
        currentTeam: "NYJ",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Baker Mayfield",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/09192018/30971.png",
        currentTeam: "CLE",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Josh Rosen",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08222018/30980.png",
        currentTeam: "ARI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Nick Mullens",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "https://s.yimg.com/xe/i/us/sp/v/nfl_cutout/players_l/08202018/30563.png",
        currentTeam: "SF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    }
];

db.Quarterback
    .remove({})
    .then(() => db.Quarterback.collection.insertMany(qbSeed))
    .then(data => {
        console.log(data.result.n + " records inserted!");
        process.exit(0);
    })
    .catch(err => {
        console.error(err);
        process.exit(1);
    });