const mongoose = require("mongoose");
const db = require("../db/models/index");

mongoose.connect(
    process.env.MONGODB_URI ||
    "mongodb://localhost/Users"
);

//QB Seed
const qbSeed = [
    {
        name: "Patrick Mahomes II",
        avgPocketTime: 2.0,
        completionPercentage: 0.45,
        image: "",
        currentTeam: "KC",
        vsDefenseCompletionPercentage: {
            "ATL": 0.45,
            "ARI": 0.45,
            "BAL": 0.45,
            "BUF": 0.45,
            "CAR": 0.45,
            "CHI": 0.45,
            "CIN": 0.45,
            "CLE": 0.45,
            "DAL": 0.45,
            "DEN": 0.45,
            "DET": 0.45,
            "GB": 0.45,
            "HOU": 0.45,
            "IND": 0.45,
            "JAX": 0.45,
            "KC": 0.45,
            "LAC": 0.45,
            "LAR": 0.45,
            "MIA": 0.45,
            "MIN": 0.45,
            "NE": 0.45,
            "NO": 0.45,
            "NYG": 0.45,
            "NYJ": 0.45,
            "OAK": 0.45,
            "PHI": 0.45,
            "PIT": 0.45,
            "SEA": 0.45,
            "SF": 0.45,
            "TB": 0.45,
            "TEN": 0.45,
            "WAS": 0.45,
        }
    },
    {
        name: "Andy Dalton",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "CIN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Andrew Luck",
        avgPocketTime: 2.2,
        completionPercentage: 0.33,
        image: "",
        currentTeam: "IND",
        vsDefenseCompletionPercentage: {
            "ATL": 0.33,
            "ARI": 0.33,
            "BAL": 0.33,
            "BUF": 0.33,
            "CAR": 0.33,
            "CHI": 0.33,
            "CIN": 0.33,
            "CLE": 0.33,
            "DAL": 0.33,
            "DEN": 0.33,
            "DET": 0.33,
            "GB": 0.33,
            "HOU": 0.33,
            "IND": 0.33,
            "JAX": 0.33,
            "KC": 0.33,
            "LAC": 0.33,
            "LAR": 0.33,
            "MIA": 0.33,
            "MIN": 0.33,
            "NE": 0.33,
            "NO": 0.33,
            "NYG": 0.33,
            "NYJ": 0.33,
            "OAK": 0.33,
            "PHI": 0.33,
            "PIT": 0.33,
            "SEA": 0.33,
            "SF": 0.33,
            "TB": 0.33,
            "TEN": 0.33,
            "WAS": 0.33
        }
    },
    {
        name: "Tom Brady",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "NE",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Drew Brees",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "NO",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Eli Manning",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "NYG",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Josh McCown",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "NYJ",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Derek Anderson",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "BUF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Philip Rivers",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "LAC",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Aaron Rodgers",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "GB",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Ben Roethlisberger",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "PIT",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Alex Smith",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "WAS",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Ryan Fitzpatrick",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "TB",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Joe Flacco",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "BAL",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Matt Ryan",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "ATL",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Matthew Stafford",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "DET",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Cam Newton",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "CAR",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Ryan Tannehill",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "MIA",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Kirk Cousins",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "MIN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Nick Foles",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "PHI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Case Keenum",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "DEN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Brock Osweiler",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "MIA",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Russell Wilson",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "SEA",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Blake Bortles",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "JAX",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Derek Carr",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "OAK",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Marcus Mariota",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "TEN",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Jameis Winston",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "TB",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Jared Goff",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "LAR",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Dak Prescott",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "DAL",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Carson Wentz",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "PHI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "C.J. Beathard",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "SF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Nathan Peterman",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "BUF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Mitchell Trubisky",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "CHI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Deshaun Watson",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "HOU",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Josh Allen",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "BUF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Sam Darnold",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "NYJ",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Baker Mayfield",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "CLE",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Josh Rosen",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "ARI",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    },
    {
        name: "Nick Mullens",
        avgPocketTime: 1.8,
        completionPercentage: 0.5,
        image: "",
        currentTeam: "SF",
        vsDefenseCompletionPercentage: {
            "ATL": 0.5,
            "ARI": 0.5,
            "BAL": 0.5,
            "BUF": 0.5,
            "CAR": 0.5,
            "CHI": 0.5,
            "CIN": 0.5,
            "CLE": 0.5,
            "DAL": 0.5,
            "DEN": 0.5,
            "DET": 0.5,
            "GB": 0.5,
            "HOU": 0.5,
            "IND": 0.5,
            "JAX": 0.5,
            "KC": 0.5,
            "LAC": 0.5,
            "LAR": 0.5,
            "MIA": 0.5,
            "MIN": 0.5,
            "NE": 0.5,
            "NO": 0.5,
            "NYG": 0.5,
            "NYJ": 0.5,
            "OAK": 0.5,
            "PHI": 0.5,
            "PIT": 0.5,
            "SEA": 0.5,
            "SF": 0.5,
            "TB": 0.5,
            "TEN": 0.5,
            "WAS": 0.5
        }
    }
];

db.Quarterback
    .remove({})
    .then(() => db.Quarterback.collection.insertMany(qbSeed))
    .then(data => {
        console.log(data.result.n + " records inserted!");
        process.exit(0);
    })
    .catch(err => {
        console.error(err);
        process.exit(1);
    });